export const REVIEWS = [
  {
    id: 0,
    courseId: 0,
    rating: 5,
    text: "This is my best course ever!",
    author: "Ibrahim Said",
    date: "2020-10-25T16:30Z",
  },
  {
    id: 1,
    courseId: 0,
    rating: 4,
    text: "The material was great, but the accessment can improve.",
    author: "John Doe",
    date: "2020-06-17T03:33Z",
  },
  {
    id: 2,
    courseId: 0,
    rating: 5,
    text: "I caught a world-record-breaking trout in this class",
    author: "Kelly Bright",
    date: "2020-02-18T18:12Z",
  },
  {
    id: 3,
    courseId: 0,
    rating: 5,
    text: "It has been such a great journey into calculus world!",
    author: "Michael Runn",
    date: "2020-08-04T20:11Z",
  },
  {
    id: 4,
    courseId: 0,
    rating: 4,
    text: "What a course",
    author: "Ann Dabramov",
    date: "2021-02-23T19:44Z",
  },
  {
    id: 5,
    courseId: 1,
    rating: 5,
    text: "This is my best course ever!",
    author: "Ibrahim Said",
    date: "2020-10-25T16:30Z",
  },
  {
    id: 6,
    courseId: 1,
    rating: 4,
    text: "The material was great, but the accessment can improve.",
    author: "John Doe",
    date: "2020-06-17T03:33Z",
  },
  {
    id: 7,
    courseId: 1,
    rating: 5,
    text: "I caught a world-record-breaking trout in this class",
    author: "Kelly Bright",
    date: "2020-02-18T18:12Z",
  },
  {
    id: 8,
    courseId: 1,
    rating: 5,
    text: "It has been such a great journey into calculus world!",
    author: "Michael Runn",
    date: "2020-08-04T20:11Z",
  },
  {
    id: 9,
    courseId: 1,
    rating: 3,
    text: "What a course",
    author: "Ann Dabramov",
    date: "2021-02-23T19:44Z",
  },
  {
    id: 10,
    courseId: 2,
    rating: 5,
    text: "This is my best course ever!",
    author: "Ibrahim Said",
    date: "2020-10-25T16:30Z",
  },
  {
    id: 11,
    courseId: 2,
    rating: 3,
    text: "The material was great, but the accessment can improve.",
    author: "John Doe",
    date: "2020-06-17T03:33Z",
  },
  {
    id: 12,
    courseId: 2,
    rating: 5,
    text: "I caught a world-record-breaking trout in this class",
    author: "Kelly Bright",
    date: "2020-02-18T18:12Z",
  },
  {
    id: 13,
    courseId: 2,
    rating: 5,
    text: "It has been such a great journey into calculus world!",
    author: "Michael Runn",
    date: "2020-08-04T20:11Z",
  },
  {
    id: 14,
    courseId: 2,
    rating: 5,
    text: "What a course",
    author: "Ann Dabramov",
    date: "2021-02-23T19:44Z",
  },
  {
    id: 15,
    courseId: 3,
    rating: 5,
    text: "This is my best course ever!",
    author: "Ibrahim Said",
    date: "2020-10-25T16:30Z",
  },
  {
    id: 16,
    courseId: 3,
    rating: 4,
    text: "The material was great, but the accessment can improve.",
    author: "John Doe",
    date: "2020-06-17T03:33Z",
  },
  {
    id: 17,
    courseId: 3,
    rating: 5,
    text: "I caught a world-record-breaking trout in this class",
    author: "Kelly Bright",
    date: "2020-02-18T18:12Z",
  },
  {
    id: 18,
    courseId: 3,
    rating: 5,
    text: "It has been such a great journey into calculus world!",
    author: "Michael Runn",
    date: "2020-08-04T20:11Z",
  },
  {
    id: 19,
    courseId: 3,
    rating: 5,
    text: "What a course",
    author: "Ann Dabramov",
    date: "2021-02-23T19:44Z",
  },
];
